export const APP_CONFIG = {
  APP_NAME: 'ミーリフト',
  VERSION: '1.0.0',
  DATABASE_NAME: 'mealift.db',
  DATABASE_VERSION: 1,
  SYNC_INTERVAL_MS: 5 * 60 * 1000,
  SYNC_MAX_RETRIES: 3,
  SUPABASE_URL: process.env.EXPO_PUBLIC_SUPABASE_URL ?? '',
  SUPABASE_ANON_KEY: process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY ?? '',
} as const;

export const LIMITS = {
  MAX_WEIGHT_KG: 300,
  MIN_WEIGHT_KG: 20,
  MAX_HEIGHT_CM: 250,
  MIN_HEIGHT_CM: 100,
  MAX_BODY_FAT_PCT: 60,
  MIN_BODY_FAT_PCT: 3,
  MAX_CALORIES: 10000,
  MIN_CALORIES: 500,
  MAX_REPS: 999,
  MAX_SETS: 20,
  MAX_WEIGHT_LIFTED_KG: 500,
  MAX_RPE: 10,
  MIN_RPE: 6,
  MAX_RIR: 5,
  MIN_RIR: 0,
  FREE_MAX_ROUTINES: 3,
} as const;
