import { DishCategory } from '../types/dish';

export interface DishSeedIngredient {
  foodName: string;
  amountG: number;
  calories: number;
  proteinG: number;
  fatG: number;
  carbG: number;
}

export interface DishSeed {
  id: string;
  nameJa: string;
  nameEn: string | null;
  category: DishCategory;
  servingDescription: string;
  ingredients: DishSeedIngredient[];
}

// ---------------------------------------------------------------------------
// Nutrition values based on 文部科学省 日本食品標準成分表 八訂
// per 100g reference → scaled to actual amount
// ---------------------------------------------------------------------------

export const DISHES: DishSeed[] = [
  // =========================================================================
  // 和食 (15品)
  // =========================================================================
  {
    id: 'dish_omurice',
    nameJa: 'オムライス',
    nameEn: 'Omurice',
    category: 'japanese',
    servingDescription: '1人前',
    ingredients: [
      { foodName: 'ご飯', amountG: 200, calories: 336, proteinG: 5.0, fatG: 0.6, carbG: 74.2 },
      { foodName: '鶏もも肉', amountG: 40, calories: 80, proteinG: 6.6, fatG: 5.7, carbG: 0.0 },
      { foodName: '卵', amountG: 100, calories: 151, proteinG: 12.3, fatG: 10.3, carbG: 0.3 },
      { foodName: '玉ねぎ', amountG: 40, calories: 15, proteinG: 0.4, fatG: 0.0, carbG: 3.5 },
      { foodName: 'バター', amountG: 10, calories: 75, proteinG: 0.1, fatG: 8.1, carbG: 0.0 },
      { foodName: 'ケチャップ', amountG: 18, calories: 21, proteinG: 0.3, fatG: 0.0, carbG: 4.7 },
      { foodName: 'サラダ油', amountG: 6, calories: 55, proteinG: 0.0, fatG: 6.0, carbG: 0.0 },
      { foodName: '牛乳', amountG: 15, calories: 10, proteinG: 0.5, fatG: 0.6, carbG: 0.7 },
      { foodName: '塩', amountG: 0.8, calories: 0, proteinG: 0.0, fatG: 0.0, carbG: 0.0 },
      { foodName: '黒胡椒', amountG: 0.1, calories: 0, proteinG: 0.0, fatG: 0.0, carbG: 0.0 },
    ],
  },
  {
    id: 'dish_curry_rice',
    nameJa: 'カレーライス',
    nameEn: 'Curry Rice',
    category: 'japanese',
    servingDescription: '1人前',
    ingredients: [
      { foodName: 'ご飯', amountG: 250, calories: 420, proteinG: 6.3, fatG: 0.8, carbG: 92.8 },
      { foodName: '豚肉', amountG: 80, calories: 181, proteinG: 14.6, fatG: 13.4, carbG: 0.2 },
      { foodName: 'じゃがいも', amountG: 60, calories: 46, proteinG: 1.0, fatG: 0.1, carbG: 10.4 },
      { foodName: 'にんじん', amountG: 30, calories: 11, proteinG: 0.2, fatG: 0.0, carbG: 2.7 },
      { foodName: '玉ねぎ', amountG: 60, calories: 22, proteinG: 0.6, fatG: 0.1, carbG: 5.3 },
      { foodName: 'カレールー', amountG: 20, calories: 102, proteinG: 1.3, fatG: 6.8, carbG: 8.6 },
      { foodName: 'サラダ油', amountG: 5, calories: 46, proteinG: 0.0, fatG: 5.0, carbG: 0.0 },
    ],
  },
  {
    id: 'dish_oyakodon',
    nameJa: '親子丼',
    nameEn: 'Oyakodon',
    category: 'japanese',
    servingDescription: '1人前',
    ingredients: [
      { foodName: 'ご飯', amountG: 250, calories: 420, proteinG: 6.3, fatG: 0.8, carbG: 92.8 },
      { foodName: '鶏もも肉', amountG: 100, calories: 200, proteinG: 16.6, fatG: 14.2, carbG: 0.0 },
      { foodName: '卵', amountG: 80, calories: 121, proteinG: 9.8, fatG: 8.2, carbG: 0.2 },
      { foodName: '玉ねぎ', amountG: 50, calories: 19, proteinG: 0.5, fatG: 0.1, carbG: 4.4 },
      { foodName: 'だし汁', amountG: 80, calories: 2, proteinG: 0.2, fatG: 0.0, carbG: 0.2 },
      { foodName: '醤油', amountG: 12, calories: 9, proteinG: 0.9, fatG: 0.0, carbG: 1.2 },
      { foodName: 'みりん', amountG: 10, calories: 24, proteinG: 0.0, fatG: 0.0, carbG: 4.3 },
    ],
  },
  {
    id: 'dish_gyudon',
    nameJa: '牛丼',
    nameEn: 'Gyudon',
    category: 'japanese',
    servingDescription: '1人前',
    ingredients: [
      { foodName: 'ご飯', amountG: 250, calories: 420, proteinG: 6.3, fatG: 0.8, carbG: 92.8 },
      { foodName: '牛バラ肉', amountG: 100, calories: 371, proteinG: 14.4, fatG: 32.9, carbG: 0.2 },
      { foodName: '玉ねぎ', amountG: 60, calories: 22, proteinG: 0.6, fatG: 0.1, carbG: 5.3 },
      { foodName: '醤油', amountG: 15, calories: 11, proteinG: 1.2, fatG: 0.0, carbG: 1.5 },
      { foodName: 'みりん', amountG: 10, calories: 24, proteinG: 0.0, fatG: 0.0, carbG: 4.3 },
      { foodName: '砂糖', amountG: 5, calories: 19, proteinG: 0.0, fatG: 0.0, carbG: 5.0 },
      { foodName: 'だし汁', amountG: 60, calories: 1, proteinG: 0.2, fatG: 0.0, carbG: 0.2 },
    ],
  },
  {
    id: 'dish_shogayaki_teishoku',
    nameJa: '豚の生姜焼き定食',
    nameEn: 'Pork Ginger Set Meal',
    category: 'japanese',
    servingDescription: '1人前',
    ingredients: [
      { foodName: 'ご飯', amountG: 200, calories: 336, proteinG: 5.0, fatG: 0.6, carbG: 74.2 },
      { foodName: '豚ロース', amountG: 120, calories: 316, proteinG: 23.0, fatG: 24.0, carbG: 0.2 },
      { foodName: 'キャベツ', amountG: 50, calories: 12, proteinG: 0.7, fatG: 0.1, carbG: 2.6 },
      { foodName: '醤油', amountG: 12, calories: 9, proteinG: 0.9, fatG: 0.0, carbG: 1.2 },
      { foodName: 'みりん', amountG: 10, calories: 24, proteinG: 0.0, fatG: 0.0, carbG: 4.3 },
      { foodName: '生姜', amountG: 5, calories: 2, proteinG: 0.0, fatG: 0.0, carbG: 0.3 },
      { foodName: 'サラダ油', amountG: 5, calories: 46, proteinG: 0.0, fatG: 5.0, carbG: 0.0 },
    ],
  },
  {
    id: 'dish_sake_shioyaki_teishoku',
    nameJa: '鮭の塩焼き定食',
    nameEn: 'Grilled Salmon Set Meal',
    category: 'japanese',
    servingDescription: '1人前',
    ingredients: [
      { foodName: 'ご飯', amountG: 200, calories: 336, proteinG: 5.0, fatG: 0.6, carbG: 74.2 },
      { foodName: '鮭', amountG: 100, calories: 133, proteinG: 22.3, fatG: 4.1, carbG: 0.1 },
      { foodName: '大根おろし', amountG: 30, calories: 5, proteinG: 0.1, fatG: 0.0, carbG: 1.2 },
      { foodName: '味噌汁', amountG: 150, calories: 30, proteinG: 2.1, fatG: 0.8, carbG: 3.2 },
      { foodName: '漬物', amountG: 20, calories: 5, proteinG: 0.2, fatG: 0.0, carbG: 1.0 },
    ],
  },
  {
    id: 'dish_nikujaga',
    nameJa: '肉じゃが',
    nameEn: 'Nikujaga',
    category: 'japanese',
    servingDescription: '1人前',
    ingredients: [
      { foodName: '豚肉', amountG: 60, calories: 136, proteinG: 10.9, fatG: 10.0, carbG: 0.1 },
      { foodName: 'じゃがいも', amountG: 150, calories: 114, proteinG: 2.4, fatG: 0.2, carbG: 26.1 },
      { foodName: 'にんじん', amountG: 30, calories: 11, proteinG: 0.2, fatG: 0.0, carbG: 2.7 },
      { foodName: '玉ねぎ', amountG: 50, calories: 19, proteinG: 0.5, fatG: 0.1, carbG: 4.4 },
      { foodName: '醤油', amountG: 15, calories: 11, proteinG: 1.2, fatG: 0.0, carbG: 1.5 },
      { foodName: 'みりん', amountG: 15, calories: 36, proteinG: 0.0, fatG: 0.0, carbG: 6.5 },
      { foodName: '砂糖', amountG: 8, calories: 31, proteinG: 0.0, fatG: 0.0, carbG: 8.0 },
    ],
  },
  {
    id: 'dish_misoshiru',
    nameJa: '味噌汁',
    nameEn: 'Miso Soup',
    category: 'japanese',
    servingDescription: '1杯',
    ingredients: [
      { foodName: '豆腐', amountG: 40, calories: 29, proteinG: 2.6, fatG: 1.8, carbG: 0.6 },
      { foodName: 'わかめ', amountG: 5, calories: 1, proteinG: 0.1, fatG: 0.0, carbG: 0.2 },
      { foodName: '味噌', amountG: 12, calories: 23, proteinG: 1.5, fatG: 0.7, carbG: 2.5 },
      { foodName: 'だし汁', amountG: 150, calories: 3, proteinG: 0.3, fatG: 0.0, carbG: 0.3 },
      { foodName: 'ねぎ', amountG: 5, calories: 2, proteinG: 0.1, fatG: 0.0, carbG: 0.4 },
    ],
  },
  {
    id: 'dish_yakizakana_teishoku',
    nameJa: '焼き魚定食',
    nameEn: 'Grilled Fish Set Meal',
    category: 'japanese',
    servingDescription: '1人前',
    ingredients: [
      { foodName: 'ご飯', amountG: 200, calories: 336, proteinG: 5.0, fatG: 0.6, carbG: 74.2 },
      { foodName: 'さば', amountG: 100, calories: 202, proteinG: 20.7, fatG: 12.1, carbG: 0.3 },
      { foodName: '大根おろし', amountG: 30, calories: 5, proteinG: 0.1, fatG: 0.0, carbG: 1.2 },
      { foodName: '醤油', amountG: 5, calories: 4, proteinG: 0.4, fatG: 0.0, carbG: 0.5 },
      { foodName: '味噌汁', amountG: 150, calories: 30, proteinG: 2.1, fatG: 0.8, carbG: 3.2 },
    ],
  },
  {
    id: 'dish_karaage_teishoku',
    nameJa: '唐揚げ定食',
    nameEn: 'Fried Chicken Set Meal',
    category: 'japanese',
    servingDescription: '1人前',
    ingredients: [
      { foodName: 'ご飯', amountG: 200, calories: 336, proteinG: 5.0, fatG: 0.6, carbG: 74.2 },
      { foodName: '鶏もも肉', amountG: 150, calories: 300, proteinG: 24.9, fatG: 21.3, carbG: 0.0 },
      { foodName: '片栗粉', amountG: 15, calories: 50, proteinG: 0.0, fatG: 0.0, carbG: 12.2 },
      { foodName: '揚げ油吸収', amountG: 15, calories: 138, proteinG: 0.0, fatG: 15.0, carbG: 0.0 },
      { foodName: '醤油', amountG: 10, calories: 7, proteinG: 0.8, fatG: 0.0, carbG: 1.0 },
      { foodName: '生姜', amountG: 5, calories: 2, proteinG: 0.0, fatG: 0.0, carbG: 0.3 },
      { foodName: 'レモン', amountG: 10, calories: 3, proteinG: 0.0, fatG: 0.0, carbG: 0.8 },
    ],
  },
  {
    id: 'dish_okonomiyaki',
    nameJa: 'お好み焼き',
    nameEn: 'Okonomiyaki',
    category: 'japanese',
    servingDescription: '1枚',
    ingredients: [
      { foodName: '小麦粉', amountG: 50, calories: 184, proteinG: 4.1, fatG: 0.9, carbG: 38.0 },
      { foodName: 'キャベツ', amountG: 100, calories: 23, proteinG: 1.3, fatG: 0.2, carbG: 5.2 },
      { foodName: '豚バラ肉', amountG: 50, calories: 186, proteinG: 7.2, fatG: 16.5, carbG: 0.1 },
      { foodName: '卵', amountG: 50, calories: 76, proteinG: 6.2, fatG: 5.2, carbG: 0.2 },
      { foodName: '天かす', amountG: 10, calories: 57, proteinG: 0.5, fatG: 4.7, carbG: 3.2 },
      { foodName: 'ソース', amountG: 15, calories: 20, proteinG: 0.2, fatG: 0.0, carbG: 4.5 },
      { foodName: 'マヨネーズ', amountG: 10, calories: 70, proteinG: 0.2, fatG: 7.5, carbG: 0.5 },
    ],
  },
  {
    id: 'dish_mapo_tofu',
    nameJa: '麻婆豆腐',
    nameEn: 'Mapo Tofu',
    category: 'japanese',
    servingDescription: '1人前',
    ingredients: [
      { foodName: '木綿豆腐', amountG: 200, calories: 144, proteinG: 13.2, fatG: 8.6, carbG: 3.2 },
      { foodName: '豚ひき肉', amountG: 60, calories: 133, proteinG: 10.6, fatG: 9.8, carbG: 0.0 },
      { foodName: '長ねぎ', amountG: 20, calories: 6, proteinG: 0.3, fatG: 0.0, carbG: 1.4 },
      { foodName: '豆板醤', amountG: 5, calories: 3, proteinG: 0.2, fatG: 0.1, carbG: 0.3 },
      { foodName: 'サラダ油', amountG: 8, calories: 74, proteinG: 0.0, fatG: 8.0, carbG: 0.0 },
      { foodName: '片栗粉', amountG: 5, calories: 17, proteinG: 0.0, fatG: 0.0, carbG: 4.1 },
    ],
  },
  {
    id: 'dish_chahan',
    nameJa: 'チャーハン',
    nameEn: 'Fried Rice',
    category: 'japanese',
    servingDescription: '1人前',
    ingredients: [
      { foodName: 'ご飯', amountG: 250, calories: 420, proteinG: 6.3, fatG: 0.8, carbG: 92.8 },
      { foodName: '卵', amountG: 50, calories: 76, proteinG: 6.2, fatG: 5.2, carbG: 0.2 },
      { foodName: 'チャーシュー', amountG: 30, calories: 51, proteinG: 5.8, fatG: 2.5, carbG: 1.5 },
      { foodName: '長ねぎ', amountG: 20, calories: 6, proteinG: 0.3, fatG: 0.0, carbG: 1.4 },
      { foodName: 'サラダ油', amountG: 10, calories: 92, proteinG: 0.0, fatG: 10.0, carbG: 0.0 },
      { foodName: '醤油', amountG: 5, calories: 4, proteinG: 0.4, fatG: 0.0, carbG: 0.5 },
    ],
  },
  {
    id: 'dish_tempura_udon',
    nameJa: '天ぷらうどん',
    nameEn: 'Tempura Udon',
    category: 'japanese',
    servingDescription: '1人前',
    ingredients: [
      { foodName: 'うどん', amountG: 250, calories: 263, proteinG: 6.5, fatG: 1.0, carbG: 54.0 },
      { foodName: '海老', amountG: 60, calories: 58, proteinG: 12.5, fatG: 0.4, carbG: 0.1 },
      { foodName: '小麦粉（衣）', amountG: 20, calories: 74, proteinG: 1.6, fatG: 0.4, carbG: 15.2 },
      { foodName: '揚げ油吸収', amountG: 10, calories: 92, proteinG: 0.0, fatG: 10.0, carbG: 0.0 },
      { foodName: 'つゆ', amountG: 200, calories: 30, proteinG: 1.8, fatG: 0.0, carbG: 5.0 },
      { foodName: 'ねぎ', amountG: 5, calories: 2, proteinG: 0.1, fatG: 0.0, carbG: 0.4 },
    ],
  },
  {
    id: 'dish_soboro_don',
    nameJa: 'そぼろ丼',
    nameEn: 'Soboro Don',
    category: 'japanese',
    servingDescription: '1人前',
    ingredients: [
      { foodName: 'ご飯', amountG: 250, calories: 420, proteinG: 6.3, fatG: 0.8, carbG: 92.8 },
      { foodName: '鶏ひき肉', amountG: 100, calories: 166, proteinG: 17.5, fatG: 10.0, carbG: 0.0 },
      { foodName: '卵', amountG: 60, calories: 91, proteinG: 7.4, fatG: 6.2, carbG: 0.2 },
      { foodName: '醤油', amountG: 15, calories: 11, proteinG: 1.2, fatG: 0.0, carbG: 1.5 },
      { foodName: '砂糖', amountG: 10, calories: 39, proteinG: 0.0, fatG: 0.0, carbG: 9.9 },
      { foodName: 'みりん', amountG: 10, calories: 24, proteinG: 0.0, fatG: 0.0, carbG: 4.3 },
    ],
  },

  // =========================================================================
  // 洋食 (10品)
  // =========================================================================
  {
    id: 'dish_hamburg_teishoku',
    nameJa: 'ハンバーグ定食',
    nameEn: 'Hamburg Steak Set Meal',
    category: 'western',
    servingDescription: '1人前',
    ingredients: [
      { foodName: 'ご飯', amountG: 200, calories: 336, proteinG: 5.0, fatG: 0.6, carbG: 74.2 },
      { foodName: '合びき肉', amountG: 150, calories: 328, proteinG: 26.1, fatG: 23.3, carbG: 0.5 },
      { foodName: '玉ねぎ', amountG: 40, calories: 15, proteinG: 0.4, fatG: 0.0, carbG: 3.5 },
      { foodName: 'パン粉', amountG: 15, calories: 56, proteinG: 2.1, fatG: 0.9, carbG: 9.6 },
      { foodName: '卵', amountG: 25, calories: 38, proteinG: 3.1, fatG: 2.6, carbG: 0.1 },
      { foodName: 'デミグラスソース', amountG: 30, calories: 25, proteinG: 0.5, fatG: 0.8, carbG: 3.8 },
      { foodName: 'サラダ油', amountG: 5, calories: 46, proteinG: 0.0, fatG: 5.0, carbG: 0.0 },
    ],
  },
  {
    id: 'dish_napolitan',
    nameJa: 'ナポリタン',
    nameEn: 'Napolitan',
    category: 'western',
    servingDescription: '1人前',
    ingredients: [
      { foodName: 'スパゲティ（茹で）', amountG: 250, calories: 413, proteinG: 13.0, fatG: 2.3, carbG: 80.0 },
      { foodName: 'ウインナー', amountG: 40, calories: 128, proteinG: 5.2, fatG: 11.5, carbG: 1.2 },
      { foodName: '玉ねぎ', amountG: 40, calories: 15, proteinG: 0.4, fatG: 0.0, carbG: 3.5 },
      { foodName: 'ピーマン', amountG: 20, calories: 4, proteinG: 0.2, fatG: 0.0, carbG: 1.0 },
      { foodName: 'ケチャップ', amountG: 30, calories: 36, proteinG: 0.5, fatG: 0.1, carbG: 7.8 },
      { foodName: 'バター', amountG: 10, calories: 75, proteinG: 0.1, fatG: 8.1, carbG: 0.0 },
    ],
  },
  {
    id: 'dish_gratin',
    nameJa: 'グラタン',
    nameEn: 'Gratin',
    category: 'western',
    servingDescription: '1人前',
    ingredients: [
      { foodName: 'マカロニ（茹で）', amountG: 100, calories: 149, proteinG: 5.2, fatG: 0.9, carbG: 28.4 },
      { foodName: '鶏肉', amountG: 60, calories: 120, proteinG: 10.0, fatG: 8.5, carbG: 0.0 },
      { foodName: '玉ねぎ', amountG: 40, calories: 15, proteinG: 0.4, fatG: 0.0, carbG: 3.5 },
      { foodName: '牛乳', amountG: 150, calories: 101, proteinG: 5.0, fatG: 5.7, carbG: 7.2 },
      { foodName: 'バター', amountG: 15, calories: 112, proteinG: 0.1, fatG: 12.2, carbG: 0.0 },
      { foodName: '小麦粉', amountG: 10, calories: 37, proteinG: 0.8, fatG: 0.2, carbG: 7.6 },
      { foodName: 'チーズ', amountG: 30, calories: 101, proteinG: 6.8, fatG: 7.8, carbG: 0.4 },
    ],
  },
  {
    id: 'dish_carbonara',
    nameJa: 'カルボナーラ',
    nameEn: 'Carbonara',
    category: 'western',
    servingDescription: '1人前',
    ingredients: [
      { foodName: 'スパゲティ（茹で）', amountG: 250, calories: 413, proteinG: 13.0, fatG: 2.3, carbG: 80.0 },
      { foodName: 'ベーコン', amountG: 30, calories: 122, proteinG: 3.9, fatG: 11.7, carbG: 0.1 },
      { foodName: '卵黄', amountG: 20, calories: 69, proteinG: 3.2, fatG: 6.0, carbG: 0.0 },
      { foodName: '生クリーム', amountG: 50, calories: 218, proteinG: 1.0, fatG: 22.5, carbG: 1.6 },
      { foodName: 'チーズ', amountG: 20, calories: 67, proteinG: 4.5, fatG: 5.2, carbG: 0.3 },
      { foodName: '黒胡椒', amountG: 0.5, calories: 2, proteinG: 0.0, fatG: 0.0, carbG: 0.3 },
    ],
  },
  {
    id: 'dish_beef_stew',
    nameJa: 'ビーフシチュー',
    nameEn: 'Beef Stew',
    category: 'western',
    servingDescription: '1人前',
    ingredients: [
      { foodName: '牛肉', amountG: 100, calories: 259, proteinG: 17.1, fatG: 19.5, carbG: 0.3 },
      { foodName: 'じゃがいも', amountG: 80, calories: 61, proteinG: 1.3, fatG: 0.1, carbG: 13.9 },
      { foodName: 'にんじん', amountG: 40, calories: 14, proteinG: 0.3, fatG: 0.0, carbG: 3.6 },
      { foodName: '玉ねぎ', amountG: 60, calories: 22, proteinG: 0.6, fatG: 0.1, carbG: 5.3 },
      { foodName: 'デミグラスソース', amountG: 50, calories: 42, proteinG: 0.8, fatG: 1.3, carbG: 6.3 },
      { foodName: 'バター', amountG: 5, calories: 37, proteinG: 0.0, fatG: 4.1, carbG: 0.0 },
    ],
  },
  {
    id: 'dish_ebi_fry_teishoku',
    nameJa: 'エビフライ定食',
    nameEn: 'Fried Shrimp Set Meal',
    category: 'western',
    servingDescription: '1人前',
    ingredients: [
      { foodName: 'ご飯', amountG: 200, calories: 336, proteinG: 5.0, fatG: 0.6, carbG: 74.2 },
      { foodName: '海老', amountG: 90, calories: 87, proteinG: 18.8, fatG: 0.5, carbG: 0.1 },
      { foodName: '小麦粉', amountG: 15, calories: 55, proteinG: 1.2, fatG: 0.3, carbG: 11.4 },
      { foodName: '卵', amountG: 20, calories: 30, proteinG: 2.5, fatG: 2.1, carbG: 0.1 },
      { foodName: 'パン粉', amountG: 20, calories: 75, proteinG: 2.8, fatG: 1.2, carbG: 12.8 },
      { foodName: '揚げ油吸収', amountG: 20, calories: 184, proteinG: 0.0, fatG: 20.0, carbG: 0.0 },
      { foodName: 'タルタルソース', amountG: 20, calories: 96, proteinG: 0.4, fatG: 9.8, carbG: 1.4 },
    ],
  },
  {
    id: 'dish_cream_stew',
    nameJa: 'クリームシチュー',
    nameEn: 'Cream Stew',
    category: 'western',
    servingDescription: '1人前',
    ingredients: [
      { foodName: '鶏肉', amountG: 80, calories: 160, proteinG: 13.3, fatG: 11.4, carbG: 0.0 },
      { foodName: 'じゃがいも', amountG: 80, calories: 61, proteinG: 1.3, fatG: 0.1, carbG: 13.9 },
      { foodName: 'にんじん', amountG: 40, calories: 14, proteinG: 0.3, fatG: 0.0, carbG: 3.6 },
      { foodName: '玉ねぎ', amountG: 60, calories: 22, proteinG: 0.6, fatG: 0.1, carbG: 5.3 },
      { foodName: '牛乳', amountG: 150, calories: 101, proteinG: 5.0, fatG: 5.7, carbG: 7.2 },
      { foodName: 'バター', amountG: 10, calories: 75, proteinG: 0.1, fatG: 8.1, carbG: 0.0 },
      { foodName: '小麦粉', amountG: 10, calories: 37, proteinG: 0.8, fatG: 0.2, carbG: 7.6 },
    ],
  },
  {
    id: 'dish_meat_sauce_spaghetti',
    nameJa: 'ミートソーススパゲティ',
    nameEn: 'Meat Sauce Spaghetti',
    category: 'western',
    servingDescription: '1人前',
    ingredients: [
      { foodName: 'スパゲティ（茹で）', amountG: 250, calories: 413, proteinG: 13.0, fatG: 2.3, carbG: 80.0 },
      { foodName: '合びき肉', amountG: 80, calories: 175, proteinG: 13.9, fatG: 12.4, carbG: 0.3 },
      { foodName: 'トマト缶', amountG: 100, calories: 20, proteinG: 0.9, fatG: 0.1, carbG: 4.0 },
      { foodName: '玉ねぎ', amountG: 40, calories: 15, proteinG: 0.4, fatG: 0.0, carbG: 3.5 },
      { foodName: 'オリーブ油', amountG: 8, calories: 74, proteinG: 0.0, fatG: 8.0, carbG: 0.0 },
      { foodName: 'チーズ', amountG: 10, calories: 34, proteinG: 2.3, fatG: 2.6, carbG: 0.1 },
    ],
  },
  {
    id: 'dish_omelette',
    nameJa: 'オムレツ',
    nameEn: 'Omelette',
    category: 'western',
    servingDescription: '1個',
    ingredients: [
      { foodName: '卵', amountG: 120, calories: 181, proteinG: 14.8, fatG: 12.4, carbG: 0.4 },
      { foodName: '牛乳', amountG: 20, calories: 13, proteinG: 0.7, fatG: 0.8, carbG: 1.0 },
      { foodName: 'バター', amountG: 10, calories: 75, proteinG: 0.1, fatG: 8.1, carbG: 0.0 },
      { foodName: '塩', amountG: 1, calories: 0, proteinG: 0.0, fatG: 0.0, carbG: 0.0 },
    ],
  },
  {
    id: 'dish_blt_sandwich',
    nameJa: 'BLTサンドイッチ',
    nameEn: 'BLT Sandwich',
    category: 'western',
    servingDescription: '1個',
    ingredients: [
      { foodName: '食パン', amountG: 60, calories: 158, proteinG: 5.6, fatG: 2.6, carbG: 28.0 },
      { foodName: 'ベーコン', amountG: 30, calories: 122, proteinG: 3.9, fatG: 11.7, carbG: 0.1 },
      { foodName: 'レタス', amountG: 20, calories: 2, proteinG: 0.1, fatG: 0.0, carbG: 0.6 },
      { foodName: 'トマト', amountG: 30, calories: 6, proteinG: 0.2, fatG: 0.0, carbG: 1.4 },
      { foodName: 'マヨネーズ', amountG: 15, calories: 105, proteinG: 0.3, fatG: 11.2, carbG: 0.7 },
    ],
  },

  // =========================================================================
  // 中華・韓国 (10品)
  // =========================================================================
  {
    id: 'dish_hoikoro',
    nameJa: '回鍋肉',
    nameEn: 'Twice-cooked Pork',
    category: 'chinese',
    servingDescription: '1人前',
    ingredients: [
      { foodName: '豚バラ肉', amountG: 100, calories: 371, proteinG: 14.4, fatG: 32.9, carbG: 0.2 },
      { foodName: 'キャベツ', amountG: 100, calories: 23, proteinG: 1.3, fatG: 0.2, carbG: 5.2 },
      { foodName: 'ピーマン', amountG: 30, calories: 7, proteinG: 0.3, fatG: 0.1, carbG: 1.5 },
      { foodName: '甜面醤', amountG: 10, calories: 26, proteinG: 0.5, fatG: 0.5, carbG: 4.5 },
      { foodName: '豆板醤', amountG: 3, calories: 2, proteinG: 0.1, fatG: 0.0, carbG: 0.2 },
      { foodName: 'サラダ油', amountG: 8, calories: 74, proteinG: 0.0, fatG: 8.0, carbG: 0.0 },
    ],
  },
  {
    id: 'dish_gyoza',
    nameJa: '餃子（6個）',
    nameEn: 'Gyoza (6pcs)',
    category: 'chinese',
    servingDescription: '6個',
    ingredients: [
      { foodName: '豚ひき肉', amountG: 60, calories: 133, proteinG: 10.6, fatG: 9.8, carbG: 0.0 },
      { foodName: 'キャベツ', amountG: 40, calories: 9, proteinG: 0.5, fatG: 0.1, carbG: 2.1 },
      { foodName: 'ニラ', amountG: 10, calories: 2, proteinG: 0.2, fatG: 0.0, carbG: 0.4 },
      { foodName: '餃子の皮', amountG: 60, calories: 174, proteinG: 5.4, fatG: 0.7, carbG: 34.3 },
      { foodName: 'サラダ油', amountG: 5, calories: 46, proteinG: 0.0, fatG: 5.0, carbG: 0.0 },
      { foodName: '醤油', amountG: 5, calories: 4, proteinG: 0.4, fatG: 0.0, carbG: 0.5 },
      { foodName: '酢', amountG: 5, calories: 1, proteinG: 0.0, fatG: 0.0, carbG: 0.4 },
    ],
  },
  {
    id: 'dish_ebi_chili',
    nameJa: 'エビチリ',
    nameEn: 'Shrimp Chili',
    category: 'chinese',
    servingDescription: '1人前',
    ingredients: [
      { foodName: '海老', amountG: 120, calories: 116, proteinG: 25.1, fatG: 0.7, carbG: 0.1 },
      { foodName: '長ねぎ', amountG: 20, calories: 6, proteinG: 0.3, fatG: 0.0, carbG: 1.4 },
      { foodName: '豆板醤', amountG: 5, calories: 3, proteinG: 0.2, fatG: 0.1, carbG: 0.3 },
      { foodName: 'ケチャップ', amountG: 15, calories: 18, proteinG: 0.3, fatG: 0.0, carbG: 3.9 },
      { foodName: '片栗粉', amountG: 5, calories: 17, proteinG: 0.0, fatG: 0.0, carbG: 4.1 },
      { foodName: 'サラダ油', amountG: 8, calories: 74, proteinG: 0.0, fatG: 8.0, carbG: 0.0 },
    ],
  },
  {
    id: 'dish_chinjao_rosu',
    nameJa: '青椒肉絲',
    nameEn: 'Pepper Steak Stir-fry',
    category: 'chinese',
    servingDescription: '1人前',
    ingredients: [
      { foodName: '豚もも肉', amountG: 80, calories: 128, proteinG: 16.4, fatG: 6.0, carbG: 0.2 },
      { foodName: 'ピーマン', amountG: 60, calories: 13, proteinG: 0.5, fatG: 0.1, carbG: 3.0 },
      { foodName: 'たけのこ', amountG: 40, calories: 11, proteinG: 1.4, fatG: 0.1, carbG: 1.7 },
      { foodName: '醤油', amountG: 8, calories: 6, proteinG: 0.6, fatG: 0.0, carbG: 0.8 },
      { foodName: 'オイスターソース', amountG: 8, calories: 9, proteinG: 0.4, fatG: 0.0, carbG: 1.5 },
      { foodName: 'サラダ油', amountG: 8, calories: 74, proteinG: 0.0, fatG: 8.0, carbG: 0.0 },
    ],
  },
  {
    id: 'dish_subuta',
    nameJa: '酢豚',
    nameEn: 'Sweet and Sour Pork',
    category: 'chinese',
    servingDescription: '1人前',
    ingredients: [
      { foodName: '豚もも肉', amountG: 100, calories: 160, proteinG: 20.5, fatG: 7.6, carbG: 0.2 },
      { foodName: '玉ねぎ', amountG: 40, calories: 15, proteinG: 0.4, fatG: 0.0, carbG: 3.5 },
      { foodName: 'にんじん', amountG: 20, calories: 7, proteinG: 0.1, fatG: 0.0, carbG: 1.8 },
      { foodName: 'ピーマン', amountG: 20, calories: 4, proteinG: 0.2, fatG: 0.0, carbG: 1.0 },
      { foodName: '酢', amountG: 15, calories: 4, proteinG: 0.0, fatG: 0.0, carbG: 1.1 },
      { foodName: '砂糖', amountG: 10, calories: 39, proteinG: 0.0, fatG: 0.0, carbG: 9.9 },
      { foodName: 'ケチャップ', amountG: 10, calories: 12, proteinG: 0.2, fatG: 0.0, carbG: 2.6 },
      { foodName: '片栗粉', amountG: 10, calories: 33, proteinG: 0.0, fatG: 0.0, carbG: 8.1 },
      { foodName: '揚げ油吸収', amountG: 10, calories: 92, proteinG: 0.0, fatG: 10.0, carbG: 0.0 },
    ],
  },
  {
    id: 'dish_tenshinhan',
    nameJa: '天津飯',
    nameEn: 'Tenshinhan',
    category: 'chinese',
    servingDescription: '1人前',
    ingredients: [
      { foodName: 'ご飯', amountG: 250, calories: 420, proteinG: 6.3, fatG: 0.8, carbG: 92.8 },
      { foodName: '卵', amountG: 100, calories: 151, proteinG: 12.3, fatG: 10.3, carbG: 0.3 },
      { foodName: 'カニカマ', amountG: 30, calories: 27, proteinG: 3.6, fatG: 0.2, carbG: 2.7 },
      { foodName: 'グリンピース', amountG: 10, calories: 9, proteinG: 0.7, fatG: 0.1, carbG: 1.4 },
      { foodName: 'あんかけ', amountG: 100, calories: 25, proteinG: 0.5, fatG: 0.1, carbG: 5.2 },
    ],
  },
  {
    id: 'dish_bibimbap',
    nameJa: 'ビビンバ',
    nameEn: 'Bibimbap',
    category: 'korean',
    servingDescription: '1人前',
    ingredients: [
      { foodName: 'ご飯', amountG: 250, calories: 420, proteinG: 6.3, fatG: 0.8, carbG: 92.8 },
      { foodName: '牛肉', amountG: 60, calories: 155, proteinG: 10.3, fatG: 11.7, carbG: 0.2 },
      { foodName: 'もやし', amountG: 40, calories: 6, proteinG: 0.7, fatG: 0.0, carbG: 1.1 },
      { foodName: 'ほうれん草', amountG: 30, calories: 6, proteinG: 0.7, fatG: 0.1, carbG: 0.9 },
      { foodName: 'にんじん', amountG: 20, calories: 7, proteinG: 0.1, fatG: 0.0, carbG: 1.8 },
      { foodName: 'キムチ', amountG: 30, calories: 14, proteinG: 0.8, fatG: 0.1, carbG: 2.2 },
      { foodName: '卵', amountG: 50, calories: 76, proteinG: 6.2, fatG: 5.2, carbG: 0.2 },
      { foodName: 'コチュジャン', amountG: 10, calories: 26, proteinG: 0.4, fatG: 0.3, carbG: 5.0 },
      { foodName: 'ごま油', amountG: 5, calories: 46, proteinG: 0.0, fatG: 5.0, carbG: 0.0 },
    ],
  },
  {
    id: 'dish_kimchi_jjigae',
    nameJa: 'キムチチゲ',
    nameEn: 'Kimchi Jjigae',
    category: 'korean',
    servingDescription: '1人前',
    ingredients: [
      { foodName: '豚バラ肉', amountG: 60, calories: 223, proteinG: 8.6, fatG: 19.7, carbG: 0.1 },
      { foodName: 'キムチ', amountG: 80, calories: 37, proteinG: 2.1, fatG: 0.3, carbG: 5.8 },
      { foodName: '豆腐', amountG: 100, calories: 72, proteinG: 6.6, fatG: 4.3, carbG: 1.6 },
      { foodName: '長ねぎ', amountG: 20, calories: 6, proteinG: 0.3, fatG: 0.0, carbG: 1.4 },
      { foodName: 'ニラ', amountG: 10, calories: 2, proteinG: 0.2, fatG: 0.0, carbG: 0.4 },
      { foodName: 'ごま油', amountG: 5, calories: 46, proteinG: 0.0, fatG: 5.0, carbG: 0.0 },
    ],
  },
  {
    id: 'dish_chinjao_don',
    nameJa: 'チンジャオロース丼',
    nameEn: 'Pepper Steak Rice Bowl',
    category: 'chinese',
    servingDescription: '1人前',
    ingredients: [
      { foodName: 'ご飯', amountG: 250, calories: 420, proteinG: 6.3, fatG: 0.8, carbG: 92.8 },
      { foodName: '牛もも肉', amountG: 80, calories: 147, proteinG: 16.4, fatG: 8.0, carbG: 0.3 },
      { foodName: 'ピーマン', amountG: 60, calories: 13, proteinG: 0.5, fatG: 0.1, carbG: 3.0 },
      { foodName: 'たけのこ', amountG: 40, calories: 11, proteinG: 1.4, fatG: 0.1, carbG: 1.7 },
      { foodName: 'オイスターソース', amountG: 10, calories: 11, proteinG: 0.5, fatG: 0.0, carbG: 1.9 },
      { foodName: 'サラダ油', amountG: 8, calories: 74, proteinG: 0.0, fatG: 8.0, carbG: 0.0 },
    ],
  },
  {
    id: 'dish_tantanmen',
    nameJa: '担々麺',
    nameEn: 'Tantanmen',
    category: 'chinese',
    servingDescription: '1人前',
    ingredients: [
      { foodName: '中華麺（茹で）', amountG: 230, calories: 322, proteinG: 11.0, fatG: 1.6, carbG: 64.4 },
      { foodName: '豚ひき肉', amountG: 40, calories: 88, proteinG: 7.1, fatG: 6.5, carbG: 0.0 },
      { foodName: 'チンゲン菜', amountG: 30, calories: 3, proteinG: 0.2, fatG: 0.0, carbG: 0.6 },
      { foodName: '練りごま', amountG: 15, calories: 95, proteinG: 3.0, fatG: 8.6, carbG: 2.7 },
      { foodName: '豆板醤', amountG: 3, calories: 2, proteinG: 0.1, fatG: 0.0, carbG: 0.2 },
      { foodName: '鶏がらスープ', amountG: 300, calories: 21, proteinG: 2.4, fatG: 0.9, carbG: 0.6 },
      { foodName: 'ラー油', amountG: 5, calories: 46, proteinG: 0.0, fatG: 5.0, carbG: 0.0 },
    ],
  },

  // =========================================================================
  // コンビニ・外食 (15品)
  // =========================================================================
  {
    id: 'dish_onigiri_sake',
    nameJa: 'おにぎり（鮭）',
    nameEn: 'Rice Ball (Salmon)',
    category: 'convenience',
    servingDescription: '1個',
    ingredients: [
      { foodName: 'ご飯', amountG: 100, calories: 168, proteinG: 2.5, fatG: 0.3, carbG: 37.1 },
      { foodName: '鮭', amountG: 10, calories: 13, proteinG: 2.2, fatG: 0.4, carbG: 0.0 },
      { foodName: '海苔', amountG: 1, calories: 2, proteinG: 0.4, fatG: 0.0, carbG: 0.1 },
    ],
  },
  {
    id: 'dish_onigiri_tuna_mayo',
    nameJa: 'おにぎり（ツナマヨ）',
    nameEn: 'Rice Ball (Tuna Mayo)',
    category: 'convenience',
    servingDescription: '1個',
    ingredients: [
      { foodName: 'ご飯', amountG: 100, calories: 168, proteinG: 2.5, fatG: 0.3, carbG: 37.1 },
      { foodName: 'ツナ', amountG: 15, calories: 38, proteinG: 2.7, fatG: 2.9, carbG: 0.1 },
      { foodName: 'マヨネーズ', amountG: 8, calories: 56, proteinG: 0.2, fatG: 6.0, carbG: 0.3 },
      { foodName: '海苔', amountG: 1, calories: 2, proteinG: 0.4, fatG: 0.0, carbG: 0.1 },
    ],
  },
  {
    id: 'dish_salad_chicken',
    nameJa: 'サラダチキン',
    nameEn: 'Salad Chicken',
    category: 'convenience',
    servingDescription: '1個',
    ingredients: [
      { foodName: '鶏むね肉（皮なし）', amountG: 115, calories: 125, proteinG: 26.5, fatG: 1.6, carbG: 0.1 },
    ],
  },
  {
    id: 'dish_makunouchi_bento',
    nameJa: 'コンビニ弁当（幕の内）',
    nameEn: 'Makunouchi Bento',
    category: 'convenience',
    servingDescription: '1個',
    ingredients: [
      { foodName: 'ご飯', amountG: 200, calories: 336, proteinG: 5.0, fatG: 0.6, carbG: 74.2 },
      { foodName: '鮭', amountG: 50, calories: 67, proteinG: 11.2, fatG: 2.1, carbG: 0.1 },
      { foodName: '卵焼き', amountG: 30, calories: 45, proteinG: 3.7, fatG: 3.1, carbG: 0.1 },
      { foodName: 'きんぴら', amountG: 20, calories: 17, proteinG: 0.3, fatG: 0.5, carbG: 2.7 },
      { foodName: '煮物', amountG: 30, calories: 22, proteinG: 0.8, fatG: 0.2, carbG: 4.2 },
      { foodName: '漬物', amountG: 10, calories: 3, proteinG: 0.1, fatG: 0.0, carbG: 0.5 },
    ],
  },
  {
    id: 'dish_cup_noodle',
    nameJa: 'カップヌードル',
    nameEn: 'Cup Noodle',
    category: 'convenience',
    servingDescription: '1個',
    ingredients: [
      { foodName: '即席麺（スープ込み）', amountG: 78, calories: 351, proteinG: 10.5, fatG: 14.6, carbG: 44.5 },
    ],
  },
  {
    id: 'dish_chain_gyudon',
    nameJa: '牛丼（チェーン並盛）',
    nameEn: 'Chain Gyudon (Regular)',
    category: 'fast_food',
    servingDescription: '並盛',
    ingredients: [
      { foodName: 'ご飯', amountG: 260, calories: 437, proteinG: 6.5, fatG: 0.8, carbG: 96.5 },
      { foodName: '牛肉', amountG: 90, calories: 334, proteinG: 13.0, fatG: 29.6, carbG: 0.2 },
      { foodName: '玉ねぎ', amountG: 50, calories: 19, proteinG: 0.5, fatG: 0.1, carbG: 4.4 },
      { foodName: 'たれ', amountG: 30, calories: 32, proteinG: 0.9, fatG: 0.0, carbG: 6.6 },
    ],
  },
  {
    id: 'dish_big_mac',
    nameJa: 'ビッグマック',
    nameEn: 'Big Mac',
    category: 'fast_food',
    servingDescription: '1個',
    ingredients: [
      { foodName: 'バンズ', amountG: 50, calories: 131, proteinG: 4.7, fatG: 1.7, carbG: 23.5 },
      { foodName: 'パティ', amountG: 90, calories: 215, proteinG: 18.5, fatG: 14.4, carbG: 0.4 },
      { foodName: 'パティ（2枚目）', amountG: 90, calories: 215, proteinG: 18.5, fatG: 14.4, carbG: 0.4 },
      { foodName: 'レタス', amountG: 10, calories: 1, proteinG: 0.1, fatG: 0.0, carbG: 0.3 },
      { foodName: 'チーズ', amountG: 20, calories: 67, proteinG: 4.5, fatG: 5.2, carbG: 0.3 },
      { foodName: 'ソース', amountG: 15, calories: 30, proteinG: 0.2, fatG: 2.3, carbG: 2.0 },
      { foodName: 'ピクルス', amountG: 5, calories: 1, proteinG: 0.0, fatG: 0.0, carbG: 0.2 },
    ],
  },
  {
    id: 'dish_tendon',
    nameJa: '天丼',
    nameEn: 'Tendon',
    category: 'japanese',
    servingDescription: '1人前',
    ingredients: [
      { foodName: 'ご飯', amountG: 250, calories: 420, proteinG: 6.3, fatG: 0.8, carbG: 92.8 },
      { foodName: '海老天', amountG: 80, calories: 173, proteinG: 12.0, fatG: 8.5, carbG: 10.8 },
      { foodName: 'かき揚げ', amountG: 60, calories: 160, proteinG: 3.2, fatG: 10.8, carbG: 12.6 },
      { foodName: 'たれ', amountG: 20, calories: 22, proteinG: 0.6, fatG: 0.0, carbG: 4.4 },
    ],
  },
  {
    id: 'dish_shoyu_ramen',
    nameJa: 'ラーメン（醤油）',
    nameEn: 'Soy Sauce Ramen',
    category: 'fast_food',
    servingDescription: '1杯',
    ingredients: [
      { foodName: '中華麺（茹で）', amountG: 230, calories: 322, proteinG: 11.0, fatG: 1.6, carbG: 64.4 },
      { foodName: 'チャーシュー', amountG: 30, calories: 51, proteinG: 5.8, fatG: 2.5, carbG: 1.5 },
      { foodName: 'メンマ', amountG: 15, calories: 3, proteinG: 0.2, fatG: 0.0, carbG: 0.5 },
      { foodName: 'ねぎ', amountG: 5, calories: 2, proteinG: 0.1, fatG: 0.0, carbG: 0.4 },
      { foodName: '醤油スープ', amountG: 300, calories: 65, proteinG: 4.5, fatG: 2.7, carbG: 5.4 },
    ],
  },
  {
    id: 'dish_tonkotsu_ramen',
    nameJa: 'ラーメン（豚骨）',
    nameEn: 'Tonkotsu Ramen',
    category: 'fast_food',
    servingDescription: '1杯',
    ingredients: [
      { foodName: '中華麺（茹で）', amountG: 230, calories: 322, proteinG: 11.0, fatG: 1.6, carbG: 64.4 },
      { foodName: 'チャーシュー', amountG: 30, calories: 51, proteinG: 5.8, fatG: 2.5, carbG: 1.5 },
      { foodName: 'きくらげ', amountG: 5, calories: 1, proteinG: 0.0, fatG: 0.0, carbG: 0.3 },
      { foodName: 'ねぎ', amountG: 5, calories: 2, proteinG: 0.1, fatG: 0.0, carbG: 0.4 },
      { foodName: '豚骨スープ', amountG: 350, calories: 140, proteinG: 7.0, fatG: 10.5, carbG: 3.5 },
    ],
  },
  {
    id: 'dish_tsukemen',
    nameJa: 'つけ麺',
    nameEn: 'Tsukemen',
    category: 'fast_food',
    servingDescription: '1人前',
    ingredients: [
      { foodName: '中華麺（茹で）', amountG: 350, calories: 490, proteinG: 16.8, fatG: 2.5, carbG: 98.0 },
      { foodName: 'チャーシュー', amountG: 30, calories: 51, proteinG: 5.8, fatG: 2.5, carbG: 1.5 },
      { foodName: 'メンマ', amountG: 10, calories: 2, proteinG: 0.2, fatG: 0.0, carbG: 0.4 },
      { foodName: 'つけ汁', amountG: 200, calories: 110, proteinG: 5.0, fatG: 5.0, carbG: 10.0 },
    ],
  },
  {
    id: 'dish_katsudon',
    nameJa: 'かつ丼',
    nameEn: 'Katsudon',
    category: 'japanese',
    servingDescription: '1人前',
    ingredients: [
      { foodName: 'ご飯', amountG: 250, calories: 420, proteinG: 6.3, fatG: 0.8, carbG: 92.8 },
      { foodName: '豚ロースカツ', amountG: 100, calories: 344, proteinG: 19.2, fatG: 25.7, carbG: 7.8 },
      { foodName: '卵', amountG: 60, calories: 91, proteinG: 7.4, fatG: 6.2, carbG: 0.2 },
      { foodName: '玉ねぎ', amountG: 30, calories: 11, proteinG: 0.3, fatG: 0.0, carbG: 2.6 },
      { foodName: 'だし汁', amountG: 80, calories: 2, proteinG: 0.2, fatG: 0.0, carbG: 0.2 },
      { foodName: '醤油', amountG: 10, calories: 7, proteinG: 0.8, fatG: 0.0, carbG: 1.0 },
      { foodName: 'みりん', amountG: 10, calories: 24, proteinG: 0.0, fatG: 0.0, carbG: 4.3 },
    ],
  },
  {
    id: 'dish_hiyashi_chuka',
    nameJa: '冷やし中華',
    nameEn: 'Cold Chinese Noodles',
    category: 'chinese',
    servingDescription: '1人前',
    ingredients: [
      { foodName: '中華麺（茹で）', amountG: 230, calories: 322, proteinG: 11.0, fatG: 1.6, carbG: 64.4 },
      { foodName: 'ハム', amountG: 20, calories: 39, proteinG: 3.3, fatG: 2.8, carbG: 0.3 },
      { foodName: '卵（薄焼き）', amountG: 30, calories: 45, proteinG: 3.7, fatG: 3.1, carbG: 0.1 },
      { foodName: 'きゅうり', amountG: 30, calories: 4, proteinG: 0.3, fatG: 0.0, carbG: 0.9 },
      { foodName: 'トマト', amountG: 20, calories: 4, proteinG: 0.1, fatG: 0.0, carbG: 0.9 },
      { foodName: 'たれ', amountG: 30, calories: 38, proteinG: 0.6, fatG: 0.6, carbG: 7.2 },
    ],
  },
  {
    id: 'dish_salmon_sushi',
    nameJa: 'サーモン寿司（5貫）',
    nameEn: 'Salmon Sushi (5pcs)',
    category: 'convenience',
    servingDescription: '5貫',
    ingredients: [
      { foodName: '酢飯', amountG: 100, calories: 179, proteinG: 2.8, fatG: 0.3, carbG: 39.9 },
      { foodName: 'サーモン', amountG: 75, calories: 163, proteinG: 15.0, fatG: 10.5, carbG: 0.1 },
      { foodName: 'わさび', amountG: 2, calories: 5, proteinG: 0.1, fatG: 0.0, carbG: 1.0 },
    ],
  },
  {
    id: 'dish_convenience_salad',
    nameJa: 'コンビニサラダ',
    nameEn: 'Convenience Store Salad',
    category: 'convenience',
    servingDescription: '1パック',
    ingredients: [
      { foodName: 'レタス', amountG: 50, calories: 6, proteinG: 0.3, fatG: 0.1, carbG: 1.4 },
      { foodName: 'キャベツ', amountG: 30, calories: 7, proteinG: 0.4, fatG: 0.1, carbG: 1.6 },
      { foodName: 'にんじん', amountG: 10, calories: 4, proteinG: 0.1, fatG: 0.0, carbG: 0.9 },
      { foodName: 'コーン', amountG: 10, calories: 10, proteinG: 0.3, fatG: 0.2, carbG: 1.8 },
      { foodName: 'ドレッシング', amountG: 15, calories: 56, proteinG: 0.1, fatG: 5.5, carbG: 1.5 },
    ],
  },
];
