// v1.5 Stage 1 Phase 1.1 — LLM abstraction types.
//
// Architectural SSoT: docs/plans/v1.5_stage_1_ai_chat_epic.md §4
// (LLM client abstraction layer) + §6 (Context injection).
//
// Design notes:
//   - The LLMClient interface is the client-side seam. The actual
//     Gemini calls run server-side in the Supabase Edge Function;
//     this layer never sees the API key (Phase 1.1 Drafting 99 —
//     server / RN runtime split honored).
//   - chat() is the streaming surface: an `AsyncIterable<string>`
//     of text deltas + a side-channel for the leading `meta` event
//     and the trailing `done` payload. Callers iterate with
//     `for await` for the deltas and consume the side-channel
//     for the assistantMessageId binding (§3 client sequence).
//   - generateStructured + generateAdvice are non-streaming.
//   - ChatOptions.idempotencyKey is REQUIRED, not optional. The
//     C2 lesson (Drafting 97 + 98) says quota-charged streaming
//     operations must carry an idempotency key end-to-end — no
//     "best-effort" semantics. Callers generate a uuid v4 per
//     intent (or reuse on retry).

import type { Session } from '@supabase/supabase-js';

// =====================================================================
// Chat messages
// =====================================================================

export type ChatRole = 'system' | 'user' | 'assistant';

export interface ChatMessage {
  role: ChatRole;
  content: string;
}

// =====================================================================
// User context (§6.2 shape)
// =====================================================================

/** Five-year age bucket. The exact birth year is intentionally
 *  withheld from the Gemini boundary; the bucket is sufficient
 *  for coaching context (Drafting checklist: PII minimization). */
export type AgeRange =
  | 'under-10'
  | '10-14'
  | '15-19'
  | '20-24'
  | '25-29'
  | '30-34'
  | '35-39'
  | '40-44'
  | '45-49'
  | '50-54'
  | '55-59'
  | '60-64'
  | '65-69'
  | '70-74'
  | '75-79'
  | '80-84'
  | '85-plus';

export interface ProfileSnapshot {
  ageRange: AgeRange;
  sex: 'male' | 'female' | 'other';
  heightCm: number;
  weightKg: number;
  goalType: 'cut' | 'bulk' | 'maintain' | 'recomp';
  activityLevel:
    | 'sedentary'
    | 'light'
    | 'moderate'
    | 'active'
    | 'very_active';
  trainingDaysPerWeek: number;
}

export interface TargetsSnapshot {
  calories: number;
  proteinG: number;
  fatG: number;
  carbG: number;
}

export interface MealNutrientSummary {
  calories: number;
  proteinG: number;
  fatG: number;
  carbG: number;
}

export interface MealSummary {
  /** 7-day rolling average per macro. */
  last7DaysAverage: MealNutrientSummary;
  /** Optional today-so-far snapshot — caller fills only when the
   *  user is mid-day. */
  todaySoFar?: MealNutrientSummary;
  /** Top 5 by frequency over the last 14 days; bounded to limit
   *  raw food name exposure at the Gemini boundary. */
  topFrequentNames: string[];
}

export interface WorkoutSummary {
  last14DaysSessions: number;
  /** Distinct routine names touched in the last 14 days. */
  routineNames: string[];
  /** Optional — Plus+ tier feature. */
  weeklyVolumeKgRepsByMuscle?: Record<string, number>;
}

export interface WeightTrendSummary {
  /** (weight today) - (weight 14d ago). Negative for cut progress. */
  last14DaysKgChange: number;
}

export interface UserContext {
  profile: ProfileSnapshot;
  targets: TargetsSnapshot;
  recentMeals: MealSummary;
  recentWorkouts: WorkoutSummary;
  recentWeightTrend: WeightTrendSummary;
}

// =====================================================================
// Streaming + non-streaming options
// =====================================================================

export interface ChatOptions {
  /** Caller can pass an AbortSignal to cancel the fetch + the
   *  server-side stream. The server detects the disconnect and
   *  routes through the 30s safety timer (§3 step 12). */
  signal?: AbortSignal;
  /** REQUIRED. uuid v4 generated by the caller. Same key on retry
   *  produces the same persisted `assistantMessageId` and skips a
   *  second Gemini call + a second `ai_usage_logs` INSERT (§3
   *  server step 2). Drafting 97 + 98. */
  idempotencyKey: string;
}

export interface AdviceOptions {
  scope: 'weekly' | 'daily';
  signal?: AbortSignal;
}

export interface StructuredOptions extends ChatOptions {
  /** JSON Schema-like object passed to Gemini's
   *  `responseSchema` / `responseMimeType: 'application/json'`
   *  configuration. */
  schema: Record<string, unknown>;
}

// =====================================================================
// Streaming side-channel
// =====================================================================

/** The `meta` line that arrives FIRST in the NDJSON stream
 *  (§3 vocabulary table + §4.3 observer hook). */
export interface ChatStreamMeta {
  assistantMessageId: string;
  conversationId: string;
  model: string;
}

/** The `done` line that arrives LAST on success (§3 vocabulary). */
export interface ChatStreamDone {
  inputTokens: number;
  outputTokens: number;
  model: string;
  finishReason: 'stop' | 'length' | 'safety';
}

/** The `AsyncIterable<string>` returned by `chat()` is augmented
 *  with two side-channels (meta + done). Implementations attach
 *  these as properties on the returned object; callers can read
 *  them WITHOUT consuming the iterable.
 *
 *  - `meta` resolves before the first chunk arrives.
 *  - `done` resolves after the iterable closes successfully. On
 *    error, the iterable rejects (`.next()` throws AIError) and
 *    the `done` promise rejects with the same AIError.
 */
export interface ChatStream extends AsyncIterable<string> {
  /** Resolves with the `meta` event payload before the first
   *  chunk. Rejects if the stream errors before meta arrives
   *  (a malformed server response). */
  readonly meta: Promise<ChatStreamMeta>;
  /** Resolves with the `done` event payload after the stream
   *  closes successfully. Rejects with the same AIError that the
   *  iterable rejects with on stream-side failure. */
  readonly done: Promise<ChatStreamDone>;
}

// =====================================================================
// LLMClient interface
// =====================================================================

export interface LLMClient {
  /** Multi-turn streaming chat. Yields text deltas as `for await`
   *  chunks; surfaces `meta` and `done` via the ChatStream
   *  side-channels (see ChatStream above). */
  chat(
    messages: ChatMessage[],
    context: UserContext,
    options: ChatOptions,
  ): ChatStream;

  /** One-shot JSON-structured generation. The Phase 1.5
   *  implementation will validate the response against the
   *  caller-supplied schema server-side (Gemini's
   *  `responseSchema` config) before the EF returns. Phase 1.1
   *  ships the wire path only; the client trusts the EF's
   *  validation and parses-then-casts. Phase 1.5 hardens the
   *  caller-side schema-check loop (Codex round 1 / I2). */
  generateStructured<T>(
    prompt: string,
    context: UserContext,
    options: StructuredOptions,
  ): Promise<T>;

  /** One-shot plain-text advice generation (surface ④). */
  generateAdvice(
    context: UserContext,
    options: AdviceOptions,
  ): Promise<string>;
}

// =====================================================================
// Helpers exported for callers and tests
// =====================================================================

/** Maps a birth year to an AgeRange bucket. The current year is
 *  optional for deterministic testing. */
export function ageRangeFromBirthYear(
  birthYear: number,
  now: Date = new Date(),
): AgeRange {
  const age = now.getFullYear() - birthYear;
  if (age < 10) return 'under-10';
  if (age < 15) return '10-14';
  if (age < 20) return '15-19';
  if (age < 25) return '20-24';
  if (age < 30) return '25-29';
  if (age < 35) return '30-34';
  if (age < 40) return '35-39';
  if (age < 45) return '40-44';
  if (age < 50) return '45-49';
  if (age < 55) return '50-54';
  if (age < 60) return '55-59';
  if (age < 65) return '60-64';
  if (age < 70) return '65-69';
  if (age < 75) return '70-74';
  if (age < 80) return '75-79';
  if (age < 85) return '80-84';
  return '85-plus';
}

/** Type guard that `LLMClient.chat()`'s return value owns the
 *  side-channels we documented. Useful in tests that mock partial
 *  implementations. */
export function isChatStream(value: unknown): value is ChatStream {
  return (
    typeof value === 'object' &&
    value !== null &&
    Symbol.asyncIterator in value &&
    'meta' in value &&
    'done' in value
  );
}

// Re-export Session for callers that need to pass a recovered
// session into chat helpers down the line.
export type { Session };
