import { dishIngredientSync } from '../dishIngredientSync';
import { runStandardSyncTests } from './standardSyncTests';

runStandardSyncTests({
  module: dishIngredientSync,
  validLocalPayload: {
    id: 'di-1',
    dish_id: 'd-1',
    food_id: 'food-chicken',
    food_name: 'Chicken Breast',
    amount_g: 100,
    calories: 165,
    protein_g: 31,
    fat_g: 3.6,
    carb_g: 0,
    sort_order: 0,
  },
  validServerRow: {
    id: 'di-1',
    user_id: 'u-1',
    dish_id: 'd-1',
    food_id: 'food-chicken',
    food_name: 'Chicken Breast',
    amount_g: 100,
    calories: 165,
    protein_g: 31,
    fat_g: 3.6,
    carb_g: 0,
    fiber_g: null,
    sodium_mg: null,
    calcium_mg: null,
    iron_mg: null,
    vitamin_a_ug: null,
    vitamin_b1_mg: null,
    vitamin_b2_mg: null,
    vitamin_b6_mg: null,
    vitamin_b12_ug: null,
    folate_ug: null,
    vitamin_c_mg: null,
    vitamin_d_ug: null,
    vitamin_e_mg: null,
    potassium_mg: null,
    magnesium_mg: null,
    zinc_mg: null,
    cholesterol_mg: null,
    saturated_fat_g: null,
    sugar_g: null,
    salt_g: null,
    sort_order: 0,
    updated_at: '2026-05-06T10:00:00Z',
    deleted_at: null,
  },
  expectedServerTable: 'user_dish_ingredients',
  expectedLocalTable: 'dish_ingredients',
});
