import { mealLogItemSync } from '../mealLogItemSync';
import { runStandardSyncTests } from './standardSyncTests';

runStandardSyncTests({
  module: mealLogItemSync,
  validLocalPayload: {
    id: 'mli-1',
    meal_log_id: 'ml-1',
    food_id: 'food-rice',
    food_name: 'White Rice',
    serving_amount: 150,
    serving_unit: 'g',
    calories: 252,
    protein_g: 4.5,
    fat_g: 0.5,
    carb_g: 56,
    fiber_g: 0.6,
    sodium_mg: 1.5,
    calcium_mg: 4.5,
    iron_mg: 0.3,
    sugar_g: 0,
  },
  validServerRow: {
    id: 'mli-1',
    user_id: 'u-1',
    meal_log_id: 'ml-1',
    food_id: 'food-rice',
    food_name: 'White Rice',
    serving_amount: 150,
    serving_unit: 'g',
    calories: 252,
    protein_g: 4.5,
    fat_g: 0.5,
    carb_g: 56,
    fiber_g: 0.6,
    sodium_mg: 1.5,
    calcium_mg: 4.5,
    iron_mg: 0.3,
    vitamin_a_ug: null,
    vitamin_b1_mg: null,
    vitamin_b2_mg: null,
    vitamin_b6_mg: null,
    vitamin_b12_ug: null,
    folate_ug: null,
    vitamin_c_mg: null,
    vitamin_d_ug: null,
    vitamin_e_mg: null,
    potassium_mg: null,
    magnesium_mg: null,
    zinc_mg: null,
    cholesterol_mg: null,
    saturated_fat_g: null,
    sugar_g: 0,
    salt_g: null,
    note: null,
    updated_at: '2026-05-06T10:00:00Z',
    deleted_at: null,
  },
  expectedServerTable: 'user_meal_log_items',
  expectedLocalTable: 'meal_log_items',
});
